/**
 * Zod schema for .meta/meta.json files.
 *
 * Reserved properties are underscore-prefixed and engine-managed.
 * All other keys are open schema (builder output).
 *
 * @module schema/meta
 */

import { z } from 'zod';

import { metaErrorSchema } from './error.js';

/** Phase names in pipeline order. */
export const phaseNames = ['architect', 'builder', 'critic'] as const;

/** A single synthesis phase name. */
export type PhaseName = (typeof phaseNames)[number];

/** Valid states for a synthesis phase. */
export const phaseStatuses = [
  'fresh',
  'stale',
  'pending',
  'running',
  'failed',
] as const;

/** A single phase status value. */
export type PhaseStatus = (typeof phaseStatuses)[number];

/** Per-phase state record. */
export type PhaseState = Record<PhaseName, PhaseStatus>;

/** Zod schema for a per-phase status value. */
const phaseStatusSchema = z.enum(phaseStatuses);

/** Zod schema for the per-meta phase state record. */
export const phaseStateSchema = z.object({
  architect: phaseStatusSchema,
  builder: phaseStatusSchema,
  critic: phaseStatusSchema,
});

/** Zod schema for the reserved (underscore-prefixed) meta.json properties. */
export const metaJsonSchema = z
  .object({
    /** Stable identity. Auto-generated on first synthesis if not provided. */
    _id: z.uuid().optional(),

    /** Human-provided steering prompt. Optional. */
    _steer: z.string().optional(),

    /**
     * Explicit cross-references to other meta owner paths.
     * Referenced metas' _content is included as architect/builder context.
     */
    _crossRefs: z.array(z.string()).optional(),

    /** Architect system prompt used this turn. Defaults from config. */
    _architect: z.string().optional(),

    /**
     * Task brief generated by the architect. Cached and reused across cycles;
     * regenerated only when triggered.
     */
    _builder: z.string().optional(),

    /** Critic system prompt used this turn. Defaults from config. */
    _critic: z.string().optional(),

    /** Timestamp of last synthesis. ISO 8601. */
    _generatedAt: z.iso.datetime().optional(),

    /** Narrative synthesis output. Rendered by watcher for embedding. */
    _content: z.string().optional(),

    /**
     * Hash of sorted file listing in scope. Detects directory structure
     * changes that trigger an architect re-run.
     */
    _structureHash: z.string().optional(),

    /**
     * Cycles since last architect run. Reset to 0 when architect runs.
     * Used with architectEvery to trigger periodic re-prompting.
     */
    _synthesisCount: z.number().int().min(0).optional(),

    /** Critic evaluation of the last synthesis. */
    _feedback: z.string().optional(),

    /**
     * Present and true on archive snapshots. Distinguishes live vs. archived
     * metas.
     */
    _archived: z.boolean().optional(),

    /** Timestamp when this snapshot was archived. ISO 8601. */
    _archivedAt: z.iso.datetime().optional(),

    /**
     * Scheduling priority. Higher = updates more often. Negative allowed;
     * normalized to min 0 at scheduling time.
     */
    _depth: z.number().optional(),

    /**
     * Emphasis multiplier for depth weighting in scheduling.
     * Default 1. Higher values increase this meta's scheduling priority
     * relative to its depth. Set to 0.5 to halve the depth effect,
     * 2 to double it, 0 to ignore depth entirely for this meta.
     */
    _emphasis: z.number().min(0).optional(),

    /** Token count from last architect subprocess call. */
    _architectTokens: z.number().int().optional(),

    /** Token count from last builder subprocess call. */
    _builderTokens: z.number().int().optional(),

    /** Token count from last critic subprocess call. */
    _criticTokens: z.number().int().optional(),

    /** Exponential moving average of architect token usage (decay 0.3). */
    _architectTokensAvg: z.number().optional(),

    /** Exponential moving average of builder token usage (decay 0.3). */
    _builderTokensAvg: z.number().optional(),

    /** Exponential moving average of critic token usage (decay 0.3). */
    _criticTokensAvg: z.number().optional(),

    /**
     * Opaque state carried across synthesis cycles for progressive work.
     * Set by the builder, passed back as context on next cycle.
     */
    _state: z.unknown().optional(),

    /**
     * Structured error from last cycle. Present when a step failed.
     * Cleared on successful cycle.
     */
    _error: metaErrorSchema.optional(),

    /** When true, this meta is skipped during staleness scheduling. Manual trigger still works. */
    _disabled: z.boolean().optional(),

    /**
     * Per-phase state machine record. Engine-managed.
     * Keyed by phase name (architect, builder, critic) with status values.
     * Persisted to survive ticks; derived on first load for back-compat.
     */
    _phaseState: phaseStateSchema.optional(),
  })
  .loose();

/** Inferred type for meta.json. */
export type MetaJson = z.infer<typeof metaJsonSchema>;
